catch (ArithmeticException e) {
      System.out.println("EXCEPTION OCCURED: " + e);
    }